### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MOVBBirthMergeAlg'

### ISSUE THREAD

**Issue by hdetering** [raphael-group/hatchet#3] opened 2019-01-23 13:55 UTC
This seems to be caused by a deprecated algorithm used in `utils/cluBB.py`:
https://github.com/raphael-group/hatchet/blob/c73f619b29b63c12aa287f8b3c10f1ffb13120ee/utils/cluBB.py#L154

As it seems it has been noted before in the context of THetA:
https://github.com/bnpy/bnpy/issues/14#issuecomment-443048158

Changing the algorithm from `'moVB'` to `'memoVB'` fixes the error - but is it methodically correct?

Cheers!
Harry

**Comment by simozacca** [comment] 2019-01-23 15:37
The error is due to the usage of the new BNPY version rather than the `dev` version, currently supported by HATCHet. Unfortunately, HATCHet currently only supports the `dev` version of BNPY (see [current issues](https://github.com/raphael-group/hatchet#currentissues)) which you can obtain in the [old bitbucket repository](https://bitbucket.org/michaelchughes/bnpy-dev/src/master/) (as well as for [THetA](https://github.com/raphael-group/THetA)).

The support for the new BNPY version (available on a [github repository](https://github.com/bnpy/bnpy)) will be available very soon for HATCHet but not before we have been able to properly test it and make sure no mayor behavior has changed.

For now, you may have two options:
1. Use the old BNPY version to be sure of the expected behavior. In this case, if you still have the same error, you may need to move or remove the repository of the new BNPY version.
2. Use the new BNPY version with the correct change that you suggested. In this case, please compare carefully the results of `cluBB` with what described in the [demos](https://github.com/raphael-group/hatchet#demos) to make sure you are obtaining meaningful and best-quality input for HATCHet.

Please let me know if the options are working for you and if you have further questions,
I will update this thread as soon as the support for the new version of BNPY will be available,

Best

**Comment by hdetering** [comment] 2019-01-24 07:53
Thanks for the quick reply @simozacca!

Using the legacy bnpy-dev version, I'm getting a different error:

```(hatchet) [...]$ python2 $HATCHET/utils/cluBB.py hatchet/bb/bulk.bb -by $HOME/src/bnpy-dev/ -o hatchet/bbc/bulk.seg -O hatchet/bbc/bulk.bbc -u 20 -e 12 -dR 0.002 -dB 0.002 -tB 0.04 -tR 0.15 -d 0.08
[2019-Jan-24 08:42:20]# Parsing and checking input arguments
[2019-Jan-24 08:42:20]# Reading the combined BB file
[2019-Jan-24 08:42:20]# Format data to cluster
[2019-Jan-24 08:42:20]# Bootstrap each bin for clustering
[2019-Jan-24 08:42:20]# Clustering bins by RD and BAF across tumor samples
[2019-Jan-24 08:42:20]## Loading BNPY
[2019-Jan-24 08:42:21]## Clustering...
Traceback (most recent call last):
  File "/home/harry/src/hatchet/utils/cluBB.py", line 319, in <module>
    main()
  File "/home/harry/src/hatchet/utils/cluBB.py", line 29, in main
    mus, sigmas, clusterAssignments, numPoints, numClusters = cluster(points=points, output=args["outsegments"], samples=samples, clouds=clouds, K=args["initclusters"], sf=args["tuning"], bnpydir=args["bnpydir"])
  File "/home/harry/src/hatchet/utils/cluBB.py", line 142, in cluster
    Data = bnpy.data.XData(X=npArray)
  File "/home/harry/src/bnpy-dev/bnpy/data/XData.py", line 97, in __init__
    self._check_dims()
  File "/home/harry/src/bnpy-dev/bnpy/data/XData.py", line 121, in _check_dims
    assert self.X.flags.owndata
AssertionError
```

This may be a problem with my data, rather than with HATCHet or BNPY...
However, with the current [GitHib version of BNPY](https://github.com/bnpy/bnpy) and `memoVB` algorithm there was no error.

So, for now I'll try my luck with option 2

> 2. Use the new BNPY version with the correct change that you suggested. In this case, please compare carefully the results of cluBB with what described in the demos to make sure you are obtaining meaningful and best-quality input for HATCHet.

Looking forward to the future release of HATCHet using a later version of BNPY.

Cheers
Harry

**Comment by simozacca** [comment] 2019-01-24 14:52
This is indeed a new and strange BNPY-specific error, if you want me to investigate this please send to me a sample of your data where this is happening and I will be happy to debug that. Also, please make sure to disable the bootstrapping (i.e. do not use the option `-u` of cluBB, it was erroneously present in the old version of the complete script but it is meant for special uses only) when running this test.

However, if you obtain meaningful results from the clustering (refer to the available demos), you can keep use the new version of BNPY which will be integrated soon anyway.

Best

**Comment by simozacca** [comment] 2019-10-04 22:41
The current version of HATCHet is now supporting both the version of `BNPY`. The implementation has been tested and it seems to work properly with both versions.

I close the issue for now but please feel free to re-open in case of other related issues.

**Closed by simozacca** 2019-10-04 22:41 UTC
