### ISSUE TITLE
Sex chromosomes with labels 'chrX' and 'chrY' not reported

### ISSUE THREAD

**Issue by nalcala** [raphael-group/hatchet#5] opened 2019-08-27 12:06 UTC
Hi,

I am running Hatchet fine but the sex chromosomes are not reported. My normal and tumor BAMs and reference use the nomenclature "chrX" and "chrY" for sex chromosomes, and I am not using any bed file.
From the logs, the sex chromosomes are excluded right away by binBAM.py, so I assume that what happens is that at the begginning of binBAM.py,  ArgParsing.py calls function extractChromosomes which does not find chrX and chrY. From my understanding of the function, it is because extractChromosomes looks for numerical chromosomes (chr1 to chr23 here https://github.com/raphael-group/hatchet/blob/0e626b0d1324b461c4014e006b3cfb85ce8e3a41/utils/ArgParsing.py#L423-L427). In that case, is it possible to add chrX and chrY to the list of chromosomes that can be detected? I don't think that just naming my sex chromosomes 23 would be a good idea, since then I would loose the difference between X and Y. It is possible that giving a bed file would solve the issue, but I feel that the automatic detection should be able to find them too.

Thanks a lot!

Nicolas

**Comment by simozacca** [comment] 2019-08-29 16:26
HATCHet currently only supports autosomes and post processing is needed to deal with the sex chromosomes. The issue is that HATCHet is based on a model of copy-number states `(a, b)` where `a,b` represent the copy numbers of the two distinct alleles of a genomic region. However, in a XY genome the sex chromosomes only have one allele each, meaning that they need to be treated differently and also B-allele frequency (BAF) -- one of the two main signals used by HATCHet and any other allele-specific copy-number method to measure the proportion of the copies of the two alleles-- is a not a signal in this case.

We are in the process of integrating explicit support for sex chromosomes in HATCHet in one of the next releases, in order to have these chromosomes directly in the factorization model (we are gonna fix one allele-specific copy number to be equal to 0). In the meanwhile I provide instructions for **temporary** solutions to deal with sex chromosomes:

- **XX genome**: in this case the user case easily include the X chromosome by adding the following two lines of code `no_chrm.add("X")`  and `chrm.add("chrX")` in the mentioned code, resulting in the following (please remember to remove or comment the lines when not in this case):

```python

 for i in range(1, 23): 
     if str(i) in normal_sq: 
         no_chrm.add(str(i)) 
     elif "chr" + str(i) in normal_sq: 
         chrm.add("chr" + str(i))
 no_chrm.add("X")
 chrm.add("chrX")
```

- **XY genome**: Compute the total copy number `c_i` of every genomic region in chromosomes X and Y in every clone `i` as the total copy number `a_i + b_i` of the region in any of the autosomes with the most similar read count and with the copy-number state `(a_i, b_)` in each clone `i` inferred by HATCHet. Therefore the steps are:

1. Compute the read counts for genomic bins across the entire genome, including the sex chromosomes. The read counts can be easily computed using for example bedtools (https://bedtools.readthedocs.io/en/latest/) in windows of 50kb.

2. For every bin `b` of chromosomes X and Y, find the bin `t` in any autosome with the most similar read count.

3. Assign to bin `b` the same total copy numbers inferred  by HATCHet for bin `t`; for example, if HATCHet inferred the copy-number states `1|1    1|0    2|0` for `t` then the total copy numbers of `b` are `2    1    2`.

We are sorry for the inconvenience and we will keep this post open until sex chromosomes will be integrated in HATCHet directly.

**Comment by nalcala** [comment] 2019-08-30 15:49
Thanks @simozacca ! I see the complications here... I might do  I am looking forward to seeing the feature implemented!

**Comment by simozacca** [comment] 2019-10-04 22:45
The current version of HATCHet is now handling BED files of genomic regions properly. Therefore, when analyzing `XX` genomes and wanting to include `chrX` in the inference, you can simply generate a BED file with the desired window size (e.g. the default 50kb) using [BEDtools](https://bedtools.readthedocs.io/en/latest/) and including `chrX`.

Please let us know if you are able to test this and we will keep the issue open for now.

**Closed** 2020-07-08 01:19 UTC

**Comment by nalcala** [comment] 2020-07-10 13:26
Great! Thanks

**Comment by miachom** [comment] 2022-11-22 16:26
Hi @simozacca and @nalcala 
I ran Hatchet with the changes recommended here in ArgParsing.py for XX genome. Although it created files such as bulk.bb.withXY, read depth ratio and snps files for chr X and Y, I don't see them in the final CN plots (1d2d) for sex chromosomes. how can I fix this in the plotting script?
